export const TIME_ZONES = [
  {timezone:"Africa/Abidjan", name: "Abidjan"},
  {timezone:"Africa/Accra", name: "Accra"},
  {timezone:"Africa/Addis_Ababa", name: "Addis Ababa"},
  {timezone:"Africa/Algiers", name: "Algiers"},
  {timezone:"Africa/Asmara", name: "Asmara"},
  {timezone:"Africa/Bamako", name: "Bamako"},
  {timezone:"Africa/Bangui", name: "Bangui"},
  {timezone:"Africa/Banjul", name: "Banjul"},
  {timezone:"Africa/Bissau", name: "Bissau"},
  {timezone:"Africa/Blantyre", name: "Blantyre"},
  {timezone:"Africa/Brazzaville", name: "Brazzaville"},
  {timezone:"Africa/Bujumbura", name: "Bujumbura"},
  {timezone:"Africa/Cairo", name: "Cairo"},
  {timezone:"Africa/Casablanca", name: "Casablanca"},
  {timezone:"Africa/Ceuta", name: "Ceuta"},
  {timezone:"Africa/Conakry", name: "Conakry"},
  {timezone:"Africa/Dakar", name: "Dakar"},
  {timezone:"Africa/Dar_es_Salaam", name: "Dar es Salaam"},
  {timezone:"Africa/Djibouti", name: "Djibouti"},
  {timezone:"Africa/Douala", name: "Douala"},
  {timezone:"Africa/El_Aaiun", name: "El Aaiun"},
  {timezone:"Africa/Freetown", name: "Freetown"},
  {timezone:"Africa/Gaborone", name: "Gaborone"},
  {timezone:"Africa/Harare", name: "Harare"},
  {timezone:"Africa/Johannesburg", name: "Johannesburg"},
  {timezone:"Africa/Juba", name: "Juba"},
  {timezone:"Africa/Kampala", name: "Kampala"},
  {timezone:"Africa/Khartoum", name: "Khartoum"},
  {timezone:"Africa/Kigali", name: "Kigali"},
  {timezone:"Africa/Kinshasa", name: "Kinshasa"},
  {timezone:"Africa/Lagos", name: "Lagos"},
  {timezone:"Africa/Libreville", name: "Libreville"},
  {timezone:"Africa/Lome", name: "Lome"},
  {timezone:"Africa/Luanda", name: "Luanda"},
  {timezone:"Africa/Lubumbashi", name: "Lubumbashi"},
  {timezone:"Africa/Lusaka", name: "Lusaka"},
  {timezone:"Africa/Malabo", name: "Malabo"},
  {timezone:"Africa/Maputo", name: "Maputo"},
  {timezone:"Africa/Maseru", name: "Maseru"},
  {timezone:"Africa/Mbabane", name: "Mbabane"},
  {timezone:"Africa/Mogadishu", name: "Mogadishu"},
  {timezone:"Africa/Monrovia", name: "Monrovia"},
  {timezone:"Africa/Nairobi", name: "Nairobi"},
  {timezone:"Africa/Ndjamena", name: "Ndjamena"},
  {timezone:"Africa/Niamey", name: "Niamey"},
  {timezone:"Africa/Nouakchott", name: "Nouakchott"},
  {timezone:"Africa/Ouagadougou", name: "Ouagadougou"},
  {timezone:"Africa/Porto-Novo", name: "Porto-Novo"},
  {timezone:"Africa/Sao_Tome", name: "Sao Tome"},
  {timezone:"Africa/Tripoli", name: "Tripoli"},
  {timezone:"Africa/Tunis", name: "Tunis"},
  {timezone:"Africa/Windhoek", name: "Windhoek"},

  {timezone:"America/Adak", name: "Adak"},
  {timezone:"America/Anchorage", name: "Anchorage"},
  {timezone:"America/Anguilla", name: "Anguilla"},
  {timezone:"America/Antigua", name: "Antigua"},
  {timezone:"America/Araguaina", name: "Araguaina"},
  {timezone:"America/Argentina/Buenos_Aires", name: "Argentina - Buenos Aires"},
  {timezone:"America/Argentina/Catamarca", name: "Argentina - Catamarca"},
  {timezone:"America/Argentina/Cordoba", name: "Argentina - Cordoba"},
  {timezone:"America/Argentina/Jujuy", name: "Argentina - Jujuy"},
  {timezone:"America/Argentina/La_Rioja", name: "Argentina - La Rioja"},
  {timezone:"America/Argentina/Mendoza", name: "Argentina - Mendoza"},
  {timezone:"America/Argentina/Rio_Gallegos", name: "Argentina - Rio Gallegos"},
  {timezone:"America/Argentina/Salta", name: "Argentina - Salta"},
  {timezone:"America/Argentina/San_Juan", name: "Argentina - San Juan"},
  {timezone:"America/Argentina/San_Luis", name: "Argentina - San Luis"},
  {timezone:"America/Argentina/Tucuman", name: "Argentina - Tucuman"},
  {timezone:"America/Argentina/Ushuaia", name: "Argentina - Ushuaia"},
  {timezone:"America/Aruba", name: "Aruba"},
  {timezone:"America/Asuncion", name: "Asuncion"},
  {timezone:"America/Atikokan", name: "Atikokan"},
  {timezone:"America/Bahia", name: "Bahia"},
  {timezone:"America/Bahia_Banderas", name: "Bahia Banderas"},
  {timezone:"America/Barbados", name: "Barbados"},
  {timezone:"America/Belem", name: "Belem"},
  {timezone:"America/Belize", name: "Belize"},
  {timezone:"America/Blanc-Sablon", name: "Blanc-Sablon"},
  {timezone:"America/Boa_Vista", name: "Boa Vista"},
  {timezone:"America/Bogota", name: "Bogota"},
  {timezone:"America/Boise", name: "Boise"},
  {timezone:"America/Cambridge_Bay", name: "Cambridge Bay"},
  {timezone:"America/Campo_Grande", name: "Campo Grande"},
  {timezone:"America/Cancun", name: "Cancun"},
  {timezone:"America/Caracas", name: "Caracas"},
  {timezone:"America/Cayenne", name: "Cayenne"},
  {timezone:"America/Cayman", name: "Cayman"},
  {timezone:"America/Chicago", name: "Chicago"},
  {timezone:"America/Chihuahua", name: "Chihuahua"},
  {timezone:"America/Costa_Rica", name: "Costa Rica"},
  {timezone:"America/Creston", name: "Creston"},
  {timezone:"America/Cuiaba", name: "Cuiaba"},
  {timezone:"America/Curacao", name: "Curacao"},
  {timezone:"America/Danmarkshavn", name: "Danmarkshavn"},
  {timezone:"America/Dawson", name: "Dawson"},
  {timezone:"America/Dawson_Creek", name: "Dawson Creek"},
  {timezone:"America/Denver", name: "Denver"},
  {timezone:"America/Detroit", name: "Detroit"},
  {timezone:"America/Dominica", name: "Dominica"},
  {timezone:"America/Edmonton", name: "Edmonton"},
  {timezone:"America/Eirunepe", name: "Eirunepe"},
  {timezone:"America/El_Salvador", name: "El Salvador"},
  {timezone:"America/Fortaleza", name: "Fortaleza"},
  {timezone:"America/Fort_Nelson", name: "Fort Nelson"},
  {timezone:"America/Glace_Bay", name: "Glace Bay"},
  {timezone:"America/Godthab", name: "Godthab"},
  {timezone:"America/Goose_Bay", name: "Goose Bay"},
  {timezone:"America/Grand_Turk", name: "Grand Turk"},
  {timezone:"America/Grenada", name: "Grenada"},
  {timezone:"America/Guadeloupe", name: "Guadeloupe"},
  {timezone:"America/Guatemala", name: "Guatemala"},
  {timezone:"America/Guayaquil", name: "Guayaquil"},
  {timezone:"America/Guyana", name: "Guyana"},
  {timezone:"America/Halifax", name: "Halifax"},
  {timezone:"America/Havana", name: "Havana"},
  {timezone:"America/Hermosillo", name: "Hermosillo"},
  {timezone:"America/Indiana/Indianapolis", name: "Indiana - Indianapolis"},
  {timezone:"America/Indiana/Knox", name: "Indiana - Knox"},
  {timezone:"America/Indiana/Marengo", name: "Indiana - Marengo"},
  {timezone:"America/Indiana/Petersburg", name: "Indiana - Petersburg"},
  {timezone:"America/Indiana/Tell_City", name: "Indiana - Tell City"},
  {timezone:"America/Indiana/Vevay", name: "Indiana - Vevay"},
  {timezone:"America/Indiana/Vincennes", name: "Indiana - Vincennes"},
  {timezone:"America/Indiana/Winamac", name: "Indiana - Winamac"},
  {timezone:"America/Inuvik", name: "Inuvik"},
  {timezone:"America/Iqaluit", name: "Iqaluit"},
  {timezone:"America/Jamaica", name: "Jamaica"},
  {timezone:"America/Juneau", name: "Juneau"},
  {timezone:"America/Kentucky/Louisville", name: "Kentucky - Louisville"},
  {timezone:"America/Kentucky/Monticello", name: "Kentucky - Monticello"},
  {timezone:"America/Kralendijk", name: "Kralendijk"},
  {timezone:"America/La_Paz", name: "La Paz"},
  {timezone:"America/Lima", name: "Lima"},
  {timezone:"America/Los_Angeles", name: "Los Angeles"},
  {timezone:"America/Lower_Princes", name: "Lower Princes"},
  {timezone:"America/Maceio", name: "Maceio"},
  {timezone:"America/Managua", name: "Managua"},
  {timezone:"America/Manaus", name: "Manaus"},
  {timezone:"America/Marigot", name: "Marigot"},
  {timezone:"America/Martinique", name: "Martinique"},
  {timezone:"America/Matamoros", name: "Matamoros"},
  {timezone:"America/Mazatlan", name: "Mazatlan"},
  {timezone:"America/Menominee", name: "Menominee"},
  {timezone:"America/Merida", name: "Merida"},
  {timezone:"America/Metlakatla", name: "Metlakatla"},
  {timezone:"America/Mexico_City", name: "Mexico City"},
  {timezone:"America/Miquelon", name: "Miquelon"},
  {timezone:"America/Moncton", name: "Moncton"},
  {timezone:"America/Monterrey", name: "Monterrey"},
  {timezone:"America/Montevideo", name: "Montevideo"},
  {timezone:"America/Montserrat", name: "Montserrat"},
  {timezone:"America/Nassau", name: "Nassau"},
  {timezone:"America/New_York", name: "New York"},
  {timezone:"America/Nipigon", name: "Nipigon"},
  {timezone:"America/Nome", name: "Nome"},
  {timezone:"America/Noronha", name: "Noronha"},
  {timezone:"America/North_Dakota/Beulah", name: "North Dakota - Beulah"},
  {timezone:"America/North_Dakota/Center", name: "North Dakota - Center"},
  {timezone:"America/North_Dakota/New_Salem", name: "North Dakota - New Salem"},
  {timezone:"America/Ojinaga", name: "Ojinaga"},
  {timezone:"America/Panama", name: "Panama"},
  {timezone:"America/Pangnirtung", name: "Pangnirtung"},
  {timezone:"America/Paramaribo", name: "Paramaribo"},
  {timezone:"America/Phoenix", name: "Phoenix"},
  {timezone:"America/Port-au-Prince", name: "Port-au-Prince"},
  {timezone:"America/Port_of_Spain", name: "Port of Spain"},
  {timezone:"America/Porto_Velho", name: "Porto Velho"},
  {timezone:"America/Puerto_Rico", name: "Puerto Rico"},
  {timezone:"America/Punta_Arenas", name: "Punta Arenas"},
  {timezone:"America/Rainy_River", name: "Rainy River"},
  {timezone:"America/Rankin_Inlet", name: "Rankin Inlet"},
  {timezone:"America/Recife", name: "Recife"},
  {timezone:"America/Regina", name: "Regina"},
  {timezone:"America/Resolute", name: "Resolute"},
  {timezone:"America/Rio_Branco", name: "Rio Branco"},
  {timezone:"America/Santarem", name: "Santarem"},
  {timezone:"America/Santiago", name: "Santiago"},
  {timezone:"America/Santo_Domingo", name: "Santo Domingo"},
  {timezone:"America/Sao_Paulo", name: "Sao Paulo"},
  {timezone:"America/Scoresbysund", name: "Scoresbysund"},
  {timezone:"America/Sitka", name: "Sitka"},
  {timezone:"America/St_Barthelemy", name: "St Barthelemy"},
  {timezone:"America/St_Johns", name: "St Johns"},
  {timezone:"America/St_Kitts", name: "St Kitts"},
  {timezone:"America/St_Lucia", name: "St Lucia"},
  {timezone:"America/St_Thomas", name: "St Thomas"},
  {timezone:"America/St_Vincent", name: "St Vincent"},
  {timezone:"America/Swift_Current", name: "Swift Current"},
  {timezone:"America/Tegucigalpa", name: "Tegucigalpa"},
  {timezone:"America/Thule", name: "Thule"},
  {timezone:"America/Thunder_Bay", name: "Thunder Bay"},
  {timezone:"America/Tijuana", name: "Tijuana"},
  {timezone:"America/Toronto", name: "Toronto"},
  {timezone:"America/Tortola", name: "Tortola"},
  {timezone:"America/Vancouver", name: "Vancouver"},
  {timezone:"America/Whitehorse", name: "Whitehorse"},
  {timezone:"America/Winnipeg", name: "Winnipeg"},
  {timezone:"America/Yakutat", name: "Yakutat"},
  {timezone:"America/Yellowknife", name: "Yellowknife"},

  {timezone:"Antarctica/Casey", name: "Casey"},
  {timezone:"Antarctica/Davis", name: "Davis"},
  {timezone:"Antarctica/DumontDUrville", name: "DumontDUrville"},
  {timezone:"Antarctica/Macquarie", name: "Macquarie"},
  {timezone:"Antarctica/Mawson", name: "Mawson"},
  {timezone:"Antarctica/McMurdo", name: "McMurdo"},
  {timezone:"Antarctica/Palmer", name: "Palmer"},
  {timezone:"Antarctica/Rothera", name: "Rothera"},
  {timezone:"Antarctica/Syowa", name: "Syowa"},
  {timezone:"Antarctica/Troll", name: "Troll"},
  {timezone:"Antarctica/Vostok", name: "Vostok"},

  {timezone:"Arctic/Longyearbyen", name: "Longyearbyen"},

  {timezone:"Asia/Aden", name: "Aden"},
  {timezone:"Asia/Almaty", name: "Almaty"},
  {timezone:"Asia/Amman", name: "Amman"},
  {timezone:"Asia/Anadyr", name: "Anadyr"},
  {timezone:"Asia/Aqtau", name: "Aqtau"},
  {timezone:"Asia/Aqtobe", name: "Aqtobe"},
  {timezone:"Asia/Ashgabat", name: "Ashgabat"},
  {timezone:"Asia/Atyrau", name: "Atyrau"},
  {timezone:"Asia/Baghdad", name: "Baghdad"},
  {timezone:"Asia/Bahrain", name: "Bahrain"},
  {timezone:"Asia/Baku", name: "Baku"},
  {timezone:"Asia/Bangkok", name: "Bangkok"},
  {timezone:"Asia/Barnaul", name: "Barnaul"},
  {timezone:"Asia/Beirut", name: "Beirut"},
  {timezone:"Asia/Bishkek", name: "Bishkek"},
  {timezone:"Asia/Brunei", name: "Brunei"},
  {timezone:"Asia/Chita", name: "Chita"},
  {timezone:"Asia/Choibalsan", name: "Choibalsan"},
  {timezone:"Asia/Colombo", name: "Colombo"},
  {timezone:"Asia/Damascus", name: "Damascus"},
  {timezone:"Asia/Dhaka", name: "Dhaka"},
  {timezone:"Asia/Dili", name: "Dili"},
  {timezone:"Asia/Dubai", name: "Dubai"},
  {timezone:"Asia/Dushanbe", name: "Dushanbe"},
  {timezone:"Asia/Famagusta", name: "Famagusta"},
  {timezone:"Asia/Gaza", name: "Gaza"},
  {timezone:"Asia/Hebron", name: "Hebron"},
  {timezone:"Asia/Ho_Chi_Minh", name: "Ho Chi Minh"},
  {timezone:"Asia/Hong_Kong", name: "Hong Kong"},
  {timezone:"Asia/Hovd", name: "Hovd"},
  {timezone:"Asia/Irkutsk", name: "Irkutsk"},
  {timezone:"Asia/Jakarta", name: "Jakarta"},
  {timezone:"Asia/Jayapura", name: "Jayapura"},
  {timezone:"Asia/Jerusalem", name: "Jerusalem"},
  {timezone:"Asia/Kabul", name: "Kabul"},
  {timezone:"Asia/Kamchatka", name: "Kamchatka"},
  {timezone:"Asia/Karachi", name: "Karachi"},
  {timezone:"Asia/Kathmandu", name: "Kathmandu"},
  {timezone:"Asia/Khandyga", name: "Khandyga"},
  {timezone:"Asia/Kolkata", name: "Kolkata"},
  {timezone:"Asia/Krasnoyarsk", name: "Krasnoyarsk"},
  {timezone:"Asia/Kuala_Lumpur", name: "Kuala Lumpur"},
  {timezone:"Asia/Kuching", name: "Kuching"},
  {timezone:"Asia/Kuwait", name: "Kuwait"},
  {timezone:"Asia/Macau", name: "Macau"},
  {timezone:"Asia/Magadan", name: "Magadan"},
  {timezone:"Asia/Makassar", name: "Makassar"},
  {timezone:"Asia/Manila", name: "Manila"},
  {timezone:"Asia/Muscat", name: "Muscat"},
  {timezone:"Asia/Nicosia", name: "Nicosia"},
  {timezone:"Asia/Novokuznetsk", name: "Novokuznetsk"},
  {timezone:"Asia/Novosibirsk", name: "Novosibirsk"},
  {timezone:"Asia/Omsk", name: "Omsk"},
  {timezone:"Asia/Oral", name: "Oral"},
  {timezone:"Asia/Phnom_Penh", name: "Phnom Penh"},
  {timezone:"Asia/Pontianak", name: "Pontianak"},
  {timezone:"Asia/Pyongyang", name: "Pyongyang"},
  {timezone:"Asia/Qatar", name: "Qatar"},
  {timezone:"Asia/Qostanay", name: "Qostanay"},
  {timezone:"Asia/Qyzylorda", name: "Qyzylorda"},
  {timezone:"Asia/Riyadh", name: "Riyadh"},
  {timezone:"Asia/Sakhalin", name: "Sakhalin"},
  {timezone:"Asia/Samarkand", name: "Samarkand"},
  {timezone:"Asia/Seoul", name: "Seoul"},
  {timezone:"Asia/Shanghai", name: "Shanghai"},
  {timezone:"Asia/Singapore", name: "Singapore"},
  {timezone:"Asia/Srednekolymsk", name: "Srednekolymsk"},
  {timezone:"Asia/Taipei", name: "Taipei"},
  {timezone:"Asia/Tashkent", name: "Tashkent"},
  {timezone:"Asia/Tbilisi", name: "Tbilisi"},
  {timezone:"Asia/Tehran", name: "Tehran"},
  {timezone:"Asia/Thimphu", name: "Thimphu"},
  {timezone:"Asia/Tokyo", name: "Tokyo"},
  {timezone:"Asia/Tomsk", name: "Tomsk"},
  {timezone:"Asia/Ulaanbaatar", name: "Ulaanbaatar"},
  {timezone:"Asia/Urumqi", name: "Urumqi"},
  {timezone:"Asia/Ust-Nera", name: "Ust-Nera"},
  {timezone:"Asia/Vientiane", name: "Vientiane"},
  {timezone:"Asia/Vladivostok", name: "Vladivostok"},
  {timezone:"Asia/Yakutsk", name: "Yakutsk"},
  {timezone:"Asia/Yangon", name: "Yangon"},
  {timezone:"Asia/Yekaterinburg", name: "Yekaterinburg"},
  {timezone:"Asia/Yerevan", name: "Yerevan"},

  {timezone:"Atlantic/Azores", name: "Azores"},
  {timezone:"Atlantic/Bermuda", name: "Bermuda"},
  {timezone:"Atlantic/Canary", name: "Canary"},
  {timezone:"Atlantic/Cape_Verde", name: "Cape Verde"},
  {timezone:"Atlantic/Faroe", name: "Faroe"},
  {timezone:"Atlantic/Madeira", name: "Madeira"},
  {timezone:"Atlantic/Reykjavik", name: "Reykjavik"},
  {timezone:"Atlantic/South_Georgia", name: "South Georgia"},
  {timezone:"Atlantic/Stanley", name: "Stanley"},
  {timezone:"Atlantic/St_Helena", name: "St Helena"},

  {timezone:"Australia/Adelaide", name: "Adelaide"},
  {timezone:"Australia/Brisbane", name: "Brisbane"},
  {timezone:"Australia/Broken_Hill", name: "Broken Hill"},
  {timezone:"Australia/Currie", name: "Currie"},
  {timezone:"Australia/Darwin", name: "Darwin"},
  {timezone:"Australia/Eucla", name: "Eucla"},
  {timezone:"Australia/Hobart", name: "Hobart"},
  {timezone:"Australia/Lindeman", name: "Lindeman"},
  {timezone:"Australia/Lord_Howe", name: "Lord Howe"},
  {timezone:"Australia/Melbourne", name: "Melbourne"},
  {timezone:"Australia/Perth", name: "Perth"},
  {timezone:"Australia/Sydney", name: "Sydney"},

  {timezone:"Europe/Amsterdam", name: "Amsterdam"},
  {timezone:"Europe/Andorra", name: "Andorra"},
  {timezone:"Europe/Astrakhan", name: "Astrakhan"},
  {timezone:"Europe/Athens", name: "Athens"},
  {timezone:"Europe/Belgrade", name: "Belgrade"},
  {timezone:"Europe/Berlin", name: "Berlin"},
  {timezone:"Europe/Bratislava", name: "Bratislava"},
  {timezone:"Europe/Brussels", name: "Brussels"},
  {timezone:"Europe/Bucharest", name: "Bucharest"},
  {timezone:"Europe/Budapest", name: "Budapest"},
  {timezone:"Europe/Busingen", name: "Busingen"},
  {timezone:"Europe/Chisinau", name: "Chisinau"},
  {timezone:"Europe/Copenhagen", name: "Copenhagen"},
  {timezone:"Europe/Dublin", name: "Dublin"},
  {timezone:"Europe/Gibraltar", name: "Gibraltar"},
  {timezone:"Europe/Guernsey", name: "Guernsey"},
  {timezone:"Europe/Helsinki", name: "Helsinki"},
  {timezone:"Europe/Isle_of_Man", name: "Isle of Man"},
  {timezone:"Europe/Istanbul", name: "Istanbul"},
  {timezone:"Europe/Jersey", name: "Jersey"},
  {timezone:"Europe/Kaliningrad", name: "Kaliningrad"},
  {timezone:"Europe/Kiev", name: "Kiev"},
  {timezone:"Europe/Kirov", name: "Kirov"},
  {timezone:"Europe/Lisbon", name: "Lisbon"},
  {timezone:"Europe/Ljubljana", name: "Ljubljana"},
  {timezone:"Europe/London", name: "London"},
  {timezone:"Europe/Luxembourg", name: "Luxembourg"},
  {timezone:"Europe/Madrid", name: "Madrid"},
  {timezone:"Europe/Malta", name: "Malta"},
  {timezone:"Europe/Mariehamn", name: "Mariehamn"},
  {timezone:"Europe/Minsk", name: "Minsk"},
  {timezone:"Europe/Monaco", name: "Monaco"},
  {timezone:"Europe/Moscow", name: "Moscow"},
  {timezone:"Europe/Oslo", name: "Oslo"},
  {timezone:"Europe/Paris", name: "Paris"},
  {timezone:"Europe/Podgorica", name: "Podgorica"},
  {timezone:"Europe/Prague", name: "Prague"},
  {timezone:"Europe/Riga", name: "Riga"},
  {timezone:"Europe/Rome", name: "Rome"},
  {timezone:"Europe/Samara", name: "Samara"},
  {timezone:"Europe/San_Marino", name: "San Marino"},
  {timezone:"Europe/Sarajevo", name: "Sarajevo"},
  {timezone:"Europe/Saratov", name: "Saratov"},
  {timezone:"Europe/Simferopol", name: "Simferopol"},
  {timezone:"Europe/Skopje", name: "Skopje"},
  {timezone:"Europe/Sofia", name: "Sofia"},
  {timezone:"Europe/Stockholm", name: "Stockholm"},
  {timezone:"Europe/Tallinn", name: "Tallinn"},
  {timezone:"Europe/Tirane", name: "Tirane"},
  {timezone:"Europe/Ulyanovsk", name: "Ulyanovsk"},
  {timezone:"Europe/Uzhgorod", name: "Uzhgorod"},
  {timezone:"Europe/Vaduz", name: "Vaduz"},
  {timezone:"Europe/Vatican", name: "Vatican"},
  {timezone:"Europe/Vienna", name: "Vienna"},
  {timezone:"Europe/Vilnius", name: "Vilnius"},
  {timezone:"Europe/Volgograd", name: "Volgograd"},
  {timezone:"Europe/Warsaw", name: "Warsaw"},
  {timezone:"Europe/Zagreb", name: "Zagreb"},
  {timezone:"Europe/Zaporozhye", name: "Zaporozhye"},
  {timezone:"Europe/Zurich", name: "Zurich"},

  {timezone:"Indian/Antananarivo", name: "Antananarivo"},
  {timezone:"Indian/Chagos", name: "Chagos"},
  {timezone:"Indian/Christmas", name: "Christmas"},
  {timezone:"Indian/Cocos", name: "Cocos"},
  {timezone:"Indian/Comoro", name: "Comoro"},
  {timezone:"Indian/Kerguelen", name: "Kerguelen"},
  {timezone:"Indian/Mahe", name: "Mahe"},
  {timezone:"Indian/Maldives", name: "Maldives"},
  {timezone:"Indian/Mauritius", name: "Mauritius"},
  {timezone:"Indian/Mayotte", name: "Mayotte"},
  {timezone:"Indian/Reunion", name: "Reunion"},

  {timezone:"Pacific/Apia", name: "Apia"},
  {timezone:"Pacific/Auckland", name: "Auckland"},
  {timezone:"Pacific/Bougainville", name: "Bougainville"},
  {timezone:"Pacific/Chatham", name: "Chatham"},
  {timezone:"Pacific/Chuuk", name: "Chuuk"},
  {timezone:"Pacific/Easter", name: "Easter"},
  {timezone:"Pacific/Efate", name: "Efate"},
  {timezone:"Pacific/Enderbury", name: "Enderbury"},
  {timezone:"Pacific/Fakaofo", name: "Fakaofo"},
  {timezone:"Pacific/Fiji", name: "Fiji"},
  {timezone:"Pacific/Funafuti", name: "Funafuti"},
  {timezone:"Pacific/Galapagos", name: "Galapagos"},
  {timezone:"Pacific/Gambier", name: "Gambier"},
  {timezone:"Pacific/Guadalcanal", name: "Guadalcanal"},
  {timezone:"Pacific/Guam", name: "Guam"},
  {timezone:"Pacific/Honolulu", name: "Honolulu"},
  {timezone:"Pacific/Kiritimati", name: "Kiritimati"},
  {timezone:"Pacific/Kosrae", name: "Kosrae"},
  {timezone:"Pacific/Kwajalein", name: "Kwajalein"},
  {timezone:"Pacific/Majuro", name: "Majuro"},
  {timezone:"Pacific/Marquesas", name: "Marquesas"},
  {timezone:"Pacific/Midway", name: "Midway"},
  {timezone:"Pacific/Nauru", name: "Nauru"},
  {timezone:"Pacific/Niue", name: "Niue"},
  {timezone:"Pacific/Norfolk", name: "Norfolk"},
  {timezone:"Pacific/Noumea", name: "Noumea"},
  {timezone:"Pacific/Pago_Pago", name: "Pago Pago"},
  {timezone:"Pacific/Palau", name: "Palau"},
  {timezone:"Pacific/Pitcairn", name: "Pitcairn"},
  {timezone:"Pacific/Pohnpei", name: "Pohnpei"},
  {timezone:"Pacific/Port_Moresby", name: "Port Moresby"},
  {timezone:"Pacific/Rarotonga", name: "Rarotonga"},
  {timezone:"Pacific/Saipan", name: "Saipan"},
  {timezone:"Pacific/Tahiti", name: "Tahiti"},
  {timezone:"Pacific/Tarawa", name: "Tarawa"},
  {timezone:"Pacific/Tongatapu", name: "Tongatapu"},
  {timezone:"Pacific/Wake", name: "Wake"},
  {timezone:"Pacific/Wallis", name: "Wallis"},
]
